# .github/workflows/deploy.yml

name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      # Explicitly include upload-artifact@v2 to avoid v3 download issue
      - name: Patch upload-artifact dependency
        uses: actions/upload-artifact@v2

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: './src'  # Adjust if your output folder is different

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
